### ISSUE TITLE
Binaries Not Running, Returning Error

### ISSUE THREAD

**Issue by geoffdavis92** [joeyespo/grip#114]
### Issue
When I attempt to execute a `grip` command, I get the following code error:

```python
Traceback (most recent call last):
  File "/usr/local/bin/grip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: Pygments>=1.6
```

I am not familiar with Python, so I can't get this resolved myself; no script runs when I input the command into my terminal window.

### System Info
OS: Mac OS X "Mavericks"
Python Version: 2.7.5
Pip Version: 6.1.1

**Comment by joeyespo** [comment]
This happens to me sometimes too. I think it's a pip / setuptools oddity, but I haven't deep-dived into the actual problem yet.

Try running this:

```bash
$ pip uninstall grip
$ pip install --upgrade pip
```

**Comment by joeyespo** [comment]
Any luck with this?

**Comment by joeyespo** [comment]
Closing for now. Feel free to reopen if you're still experiencing this and the above snippet doesn't help.

**Comment by geoffdavis92** [comment]
Yes this worked! Thank you
