### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xae in position 161: invalid start byte

### ISSUE THREAD

**Issue by AnthonyARM** [joeyespo/grip#118]
This happens both with --export and without:

```
* Running on http://localhost:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [08/May/2015 15:04:36] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/grip-3.2.0-py2.7.egg/grip/server.py", line 134, in render
    render_text = _read_file_or_404(filename)
  File "/usr/local/lib/python2.7/dist-packages/grip-3.2.0-py2.7.egg/grip/server.py", line 366, in _read_file_or_404
    return f.read()
  File "/usr/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xae in position 161: invalid start byte
```

**Comment by joeyespo** [comment]
Looks like you're reading from a file with an encoding that isn't UTF-8 or ASCII. And change you could copy/paste the file into a [gist](http://gist.github.com/)?

Also, what OS are you on?

**Comment by joeyespo** [comment]
Just deployed `v3.3.0`. It fixes a lot of Unicode problems. Could you try it out with `pip install --upgrade grip` and see if it fixes this issue? Feel free to re-open if not.
