### ISSUE TITLE
Export feature not working in Python 3.4.3

### ISSUE THREAD

**Issue by alanmb** [joeyespo/grip#129]
Keep getting "TypeError: can't use a string pattern on a bytes-like object" error when running grip in Python 3.4.3. Tried doing it in Python 2.7 and it worked without an issue.

**Comment by joeyespo** [comment]
Hey @alanmb, mind posting the full stack trace on here? There's a chance this got fixed already (in the next release, that is).

Thanks!

**Comment by alanmb** [comment]
Sure! Here it is:

```    
D:\inetpub\wwwroot\dyno\DYNO_Docs>py -3 export-markdown.py
Exporting to CompositePlotter.html
Traceback (most recent call last):
  File "export-markdown.py", line 8, in <module>
    export(i, gfm=True, context=None, username=None, password=None, render_offline=False, render_wide=False, render_inline=True, out_filename=exportedFileName)
  File "C:\Python34\lib\site-packages\grip\exporter.py", line 36, in export
    render_offline, render_wide, render_inline)
  File "C:\Python34\lib\site-packages\grip\exporter.py", line 18, in render_page

    return render_app(app)
  File "C:\Python34\lib\site-packages\grip\renderer.py", line 8, in render_app
    response = c.get('/')
  File "C:\Python34\lib\site-packages\werkzeug\test.py", line 774, in get
    return self.open(*args, **kw)
  File "C:\Python34\lib\site-packages\flask\testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "C:\Python34\lib\site-packages\werkzeug\test.py", line 742, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "C:\Python34\lib\site-packages\werkzeug\test.py", line 659, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "C:\Python34\lib\site-packages\werkzeug\test.py", line 867, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "C:\Python34\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python34\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python34\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python34\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python34\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1470, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1497, in try_trigger_before_first_request_functions
    func()
  File "C:\Python34\lib\site-packages\grip\server.py", line 111, in retrieve_styles
    app.config['STYLE_ASSET_URLS_INLINE']))
  File "C:\Python34\lib\site-packages\grip\server.py", line 304, in _get_styles
    content = re.sub(asset_pattern, match_asset, _download(app, style_url))
  File "C:\Python34\lib\re.py", line 179, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: can't use a string pattern on a bytes-like object
```

Thanks for the quick response. Great work by the way!

**Comment by joeyespo** [comment]
Thanks :-D 

Ah, yeah. Looks like I need to step up my game. #100 is an issue from last month with the same problem. Cloning from master should solve your two current issues.

Going to close them so I can focus on the open ones. Feel free to re-open if the latest code doesn't actually solve them.

Thanks, @alanmb!

**Comment by joeyespo** [comment]
FYI, just deployed `v3.3.0` which contains the fix. Be sure to `pip install --upgrade grip` and let me know if you're still seeing problems.

**Comment by joeyespo** [comment]
FYI, just deployed `v3.3.0` which contains the fix. Be sure to `pip install --upgrade grip` and let me know if you're still seeing problems.
