### ISSUE TITLE
Error while displaying special characters

### ISSUE THREAD

**Issue by L30Bola** [joeyespo/grip#187]
So I have file with characters like <kbd>ê</kbd> <kbd>õ</kbd> <kbd>á</kbd> <kbd>ç</kbd> <kbd>ì</kbd>. When I start grip it looks normal (` * Running on http://localhost:6419/ (Press CTRL+C to quit)`) but when I open the browser window and navigate to localhost:6419, it gives me a 500 Internal Error. On the terminal windows this is the Traceback:
```bash
[2016-07-08 18:59:47,107] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\site-packages\grip\app.py", line 163, in _render_page
    text = self.reader.read(subpath)
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\site-packages\grip\readers.py", line 265, in read
    return self._read_text(filename)
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\site-packages\grip\readers.py", line 146, in _read_text
    return f.read()
  File "c:\users\coppe\appdata\local\programs\python\python35\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 68: invalid start byte
127.0.0.1 - - [08/Jul/2016 18:59:47] "GET / HTTP/1.1" 500 -
```

This error only shows up on Windows (tested on Windows 10, Firefox/Chrome). On my Linux (Fedora 23) it is working without issues.

**Comment by Efreeto** [comment]
Thank you for documenting this error @L30Bola.
I also had this issue for <kbd>“</kbd> and <kbd>”</kbd>, but I wouldn't even have guessed it if you hadn't documented this bug.

**Comment by skandix** [comment]
is this something that is prioritized to fix? It occurs both in python 2.7 and python 3.4.. 
it triggers on my norwegian special characters 'æ ø å'
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 167: invalid continuation byte
```
