### ISSUE TITLE
cannot run two server instances concurrently[Address already in use]

### ISSUE THREAD

**Issue by ehzShelter** [joeyespo/grip#211]
###### Error Log

Traceback (most recent call last):
  File "/home/hell/.myPython/bin/grip", line 9, in <module>
    load_entry_point('grip==4.3.2', 'console_scripts', 'grip')()
  File "/home/hell/.myPython/lib/python3.5/site-packages/grip/command.py", line 127, in main
    args['--browser'], args['--quiet'], None)
  File "/home/hell/.myPython/lib/python3.5/site-packages/grip/api.py", line 60, in serve
    app.run(host, port, open_browser=browser)
  File "/home/hell/.myPython/lib/python3.5/site-packages/grip/app.py", line 416, in run
    threaded=True)
  File "/home/hell/.myPython/lib/python3.5/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/home/hell/.myPython/lib/python3.5/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/home/hell/.myPython/lib/python3.5/site-packages/werkzeug/serving.py", line 656, in inner
    fd=fd)
  File "/home/hell/.myPython/lib/python3.5/site-packages/werkzeug/serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/hell/.myPython/lib/python3.5/site-packages/werkzeug/serving.py", line 464, in **init**
    HTTPServer.**init**(self, (host, int(port)), handler)
  File "/home/hell/.myPython/lib/python3.5/socketserver.py", line 440, in **init**
    self.server_bind()
  File "/home/hell/.myPython/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/hell/.myPython/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by joeyespo** [comment]
Yeah it's probably a good idea to show a friendlier error message. I'll mark this as a bug to handle that.

As for randomizing the port, that's already handled (see #195), with `grip 0`.

Thanks for the issue, @ehzShelter!

**Comment by ehzShelter** [comment]
Welcome :D ... Actually, I observed the issue subconsciously, Not intentionally !

**Comment by davisjam** [comment]
@ehzShelter The error message in #216 would look like this:

> OSError: [Errno 98] Address already in use
> This port is in use. Is a grip server already running? Kill it or specify another port.

What do you think?
