### ISSUE TITLE
Using a token causes: 500 Internal Server Error

### ISSUE THREAD

**Issue by natemccurdy** [joeyespo/grip#221]
Hi, when I set a token in `~/.grip/settings.py`and load a page from grip, I see "500 Internal Server Error" in the web browser. Here's the dump from the command line:

```
 * Using personal access token
 * Running on http://localhost:6419/ (Press CTRL+C to quit)
[2016-12-09 16:45:54,144] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/grip/app.py", line 174, in _render_page
    content = self.renderer.render(text, self.auth)
  File "/usr/local/lib/python2.7/site-packages/grip/renderers.py", line 100, in render
    r = requests.post(url, headers=headers, data=data, auth=auth)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 527, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python2.7/site-packages/requests/auth.py", line 68, in __call__
    r.headers['Authorization'] = _basic_auth_str(self.username, self.password)
  File "/usr/local/lib/python2.7/site-packages/requests/auth.py", line 38, in _basic_auth_str
    b64encode(b':'.join((username, password))).strip()
TypeError: sequence item 0: expected string, NoneType found
127.0.0.1 - - [09/Dec/2016 16:45:54] "GET / HTTP/1.1" 500 -
```

My `~/.grip/settings.py` looks like this:

```
def find_token():
    import subprocess
    import re
    cmd = ['security', 'find-generic-password', '-gs', 'grip_github_token']
    pwinfo = subprocess.Popen(cmd, stdout = subprocess.PIPE,
            stderr = subprocess.PIPE)
    pwline = pwinfo.stderr.read().strip()
    return re.sub('password: "(.*)"', '\\1', pwline)

PASSWORD = find_token()
```

This has worked fine for the past 2 years or so. I upgraded Grip to `4.3.2`, and that hasn't helped.

If I remove the `PASSWORD` field from settings.py, I am able to load the grip web page..

**Comment by joeyespo** [comment]
Interesting! I'll look now more closely tonight, but for now, could you
check that find_token is returning a string. Looks like it might be
returning None instead.

On Fri, Dec 9, 2016, 5:52 PM Nate McCurdy <notifications@github.com> wrote:

Hi, when I set a token in ~/.grip/settings.pyand load a page from grip, I
see "500 Internal Server Error" in the web browser. Here's the dump from
the command line:

 * Using personal access token
 * Running on http://localhost:6419/ (Press CTRL+C to quit)
[2016-12-09 16:45:54,144] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line
1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line
1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line
1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line
1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line
1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/grip/app.py", line 174,
in _render_page
    content = self.renderer.render(text, self.auth)
  File "/usr/local/lib/python2.7/site-packages/grip/renderers.py",
line 100, in render
    r = requests.post(url, headers=headers, data=data, auth=auth)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line
110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line
56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py",
line 474, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py",
line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/site-packages/requests/models.py",
line 306, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python2.7/site-packages/requests/models.py",
line 527, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python2.7/site-packages/requests/auth.py", line
68, in __call__
    r.headers['Authorization'] = _basic_auth_str(self.username, self.password)
  File "/usr/local/lib/python2.7/site-packages/requests/auth.py", line
38, in _basic_auth_str
    b64encode(b':'.join((username, password))).strip()
TypeError: sequence item 0: expected string, NoneType found
127.0.0.1 - - [09/Dec/2016 16:45:54] "GET / HTTP/1.1" 500 -

My ~/.grip/settings.py looks like this:

def find_token():
    import subprocess
    import re
    cmd = ['security', 'find-generic-password', '-gs', 'grip_github_token']
    pwinfo = subprocess.Popen(cmd, stdout = subprocess.PIPE,
            stderr = subprocess.PIPE)
    pwline = pwinfo.stderr.read().strip()
    return re.sub('password: "(.*)"', '\\1', pwline)

PASSWORD = find_token()

This has worked fine for the past 2 years or so. I upgraded Grip to 4.3.2,
and that hasn't helped.

If I remove the PASSWORD field from settings.py, I am able to load the grip
web page..

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/joeyespo/grip/issues/221>, or mute the thread

**Comment by natemccurdy** [comment]
Thanks for looking into this!

Confirmed that yes, the `find_token()` call is returning a string:
<img width="542" alt="settings returns string" src="https://cloud.githubusercontent.com/assets/10200384/21068630/d6ff1648-be38-11e6-814d-0ac932eef28a.png">

Also confirmed that the token is still valid in GitHub.

**Comment by joeyespo** [comment]
Looks like the `auth` argument may have become more strict.

Could you try two things?

1. See what version of `requests` you're using

   ```bash
   $ pip show requests
   ```
   
   (Mine is 2.12.1.)

2. Try adding the following to your `settings.py` file

   ```py
   USERNAME = ''
   ```

If (2) fixes it, I'll patch the codebase to handle this edge case so it's less of a surprise.

Thanks!

**Comment by natemccurdy** [comment]
1. requests version: `2.12.3`
2. That worked!

Looks like it was that `USERNAME` needed to be set to the empty string.

**Comment by joeyespo** [comment]
Ok, excellent!

I just pushed a fix to `master`. I'll publish a new release soon.

Thanks for the issue, @natemccurdy!
