### ISSUE TITLE
"Exception in thread" error when modifying and saving README.md

### ISSUE THREAD

**Issue by erikrtn** [joeyespo/grip#227]
Using a fresh install via `pip3 install grip`, but when I make a change to my `README.md`, I get this exception:

```
 * Change detected in README.md, refreshing
127.0.0.1 - - [17/Feb/2017 17:06:42] "GET /__/grip/refresh/ HTTP/1.1" 200 -
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

Seems like it is looking in Python 2 for stuff though.

This error is reproducible by making any change whatsoever to `README.md` and saving it.

**Comment by joeyespo** [comment]
Hmm. Seems there's some incompatibility with the Python 3 executable and and Python 2 builtin libraries. That isn't surprising. I'm curious how a pip3 installation is being mixed with Python 2. (Grip doesn't seek out Python 2 explicitly.)

Are your PYTHONPATHs being crossed somewhere? What happens if you `pip install grip` instead?

**Comment by erikrtn** [comment]
> Are your PYTHONPATHs being crossed somewhere?

They appear separate. Here's 2.7:

```
$ python -c "import sys; print(sys.path)"
['', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC']
```

and here is 3.6:

```
$ python3 -c "import sys; print(sys.path)"
['', '/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages']
```

> What happens if you `pip install grip` instead?

I only have pip3 on my machine, not pip. Trying quite hard to do everything in Python 3.

**Comment by joeyespo** [comment]
Ok, those seem normal.

Python 2.7 does come prepackaged with pip now. I wonder if something happened during your transition to 3.

Try running Grip this way to be sure it's running in Python 3.

```
$ python3 -m grip
```

**Comment by erikrtn** [comment]
That is just the command I was looking for! No more error. Thank you for being so prompt too.

I thought #54 changed `grip` to run on Python 3 by default though?

**Comment by joeyespo** [comment]
Happy to help 😃 

`grip` will be run on whichever pip version installs it. I'll bet there's some wires crossed somewhere since running `pip3 install grip` then running `grip` is importing Python 2 packages. I'd recommend re-installing Python. You'll know it's fixed when grip runs fully in the environment you installed it in.

**Comment by erikrtn** [comment]
Good suggestion. I removed all traces of pip and pip3, reinstalled Python 3 via Homebrew, and reinstalled grip via `pip3 install grip`. Now it works as intended! 👍

**Comment by joeyespo** [comment]
Awesome! Glad that worked for you 😃
