### ISSUE TITLE
Unauthorized for url: https://api.github.com/markd own/raw

### ISSUE THREAD

**Issue by aemonge** [joeyespo/grip#277]
```bash
 aemonge   ~/u/d/cells-hybrid-solution    master  grip pub-sub.propursal.md --export --user aem
onge --pass '*******************'
Exporting to pub-sub.propursal.html
[2018-07-11 11:37:07,038] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/grip/app.py", line 174, in _render_page
    content = self.renderer.render(text, self.auth)
  File "/usr/lib/python3.6/site-packages/grip/renderers.py", line 78, in render
    r.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/markd
own/raw
```

*versions*
```bash
 aemonge   ~/u/d/cells-hybrid-solution    master  node --version ; npm --version ; grip --versi
on
v8.9.4
6.0.1
Grip 4.4.0
```

**Comment by dieterplex** [comment]
In case you have 2FA enabled, use personal access token as password.
https://github.com/joeyespo/grip/issues/35#issuecomment-191944696
