### ISSUE TITLE
Having issues with latest release, 4.6.2

### ISSUE THREAD

**Issue by thomassantosh** [joeyespo/grip#379]
Had upgraded to the 4.6.2 release. 

Ran `grip <filename>` as usual and got this traceback:

`Traceback (most recent call last):
  File "/usr/local/bin/grip", line 5, in <module>
    from grip import main
  File "/usr/local/Cellar/grip/4.6.2_1/libexec/lib/python3.12/site-packages/grip/__init__.py", line 19, in <module>
    from .api import (
  File "/usr/local/Cellar/grip/4.6.2_1/libexec/lib/python3.12/site-packages/grip/api.py", line 8, in <module>
    from .app import Grip
  File "/usr/local/Cellar/grip/4.6.2_1/libexec/lib/python3.12/site-packages/grip/app.py", line 36, in <module>
    from .renderers import GitHubRenderer, ReadmeRenderer
  File "/usr/local/Cellar/grip/4.6.2_1/libexec/lib/python3.12/site-packages/grip/renderers.py", line 11, in <module>
    from .vendor.mdx_urlize import UrlizeExtension
  File "/usr/local/Cellar/grip/4.6.2_1/libexec/lib/python3.12/site-packages/grip/vendor/mdx_urlize.py", line 49, in <module>
    class UrlizePattern(markdown.inlinepatterns.Pattern):
                        ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown' has no attribute 'inlinepatterns'`

**Comment by thomassantosh** [comment]
This seems to have been resolved with the recent update. 4.6.2_2? Thanks!
