### ISSUE TITLE
grip Command Fails with ModuleNotFoundError: No module named 'path_and_address'

### ISSUE THREAD

**Issue by ashish-kus** [joeyespo/grip#394]
I installed grip using yay -S python-grip, but when trying to use the grip command, I encountered the following error:

`  ModuleNotFoundError: No module named path_and_address `

Steps to Reproduce:
    1. Install grip using yay -S python-grip.
    2. Run the grip command.

Error Log

`
Traceback (most recent call last):
  File "/usr/bin/grip", line 33, in <module>
    sys.exit(load_entry_point('grip==4.6.1', 'console_scripts', 'grip')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/grip", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/grip/__init__.py", line 23, in <module>
    from .command import main
  File "/usr/lib/python3.12/site-packages/grip/command.py", line 52, in <module>
    from path_and_address import resolve, split_address
ModuleNotFoundError: No module named 'path_and_address'
`

**Comment by chrishrb** [comment]
Hi, I think that grip is no longer maintained, so I created my own version of it in go - without the need of the github api. Check it out: https://github.com/chrishrb/go-grip. Feel free to raise issues or feature requests!

**Comment by ernstki** [comment]
@ashish-kus I think it's best to use one of [the installation methods](https://github.com/joeyespo/grip?tab=readme-ov-file#installation) that the author included in the README, and report back if you still have a problem.

Otherwise, it's an AUR packaging problem, and this probably isn't the place to address that. I'm not an Arch user, but I imagine there are forums and possibly a dedicated issue tracker for AUR packages. Please let us know if you found a solution elsewhere, though!

**Comment by danielml-mx** [comment]
If anyone stumbles onto this issue, at least in my case it was due to an out-of-date `python-path-and-address` package. Running `yay -S python-path-and-address` fixed it.
