### ISSUE TITLE
Getting traceback attempting first use

### ISSUE THREAD

**Issue by textractor** [joeyespo/grip#83]
I have grip 3.0.0 installed on Mac Mavericks. I am getting Traceback when trying to run it:

```
Traceback (most recent call last):
  File "/usr/local/bin/grip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests==2.3.0
```
I looked at another similar issue, and ran the following:

```
$ which python
/usr/bin/python
$ which pip
/usr/local/bin/pip
```

Not sure how to interpret these or what to do next.

**Comment by joeyespo** [comment]
I just unpinned the dependencies in 1ad0b42d70f0340e34b0f30236ef8a8ed106c6f2. Could you try cloning the latest and running `python setup.py install` without `sudo` and see if that works for you?

**Comment by laomo** [comment]
@joeyespo thinks

**Comment by joeyespo** [comment]
Just released a new version that might fix this. `pip install --upgrade grip`, and reopen if this is still an unresolved issue.
